[build]
  command = "echo 'No build step'"
  publish = "/public"  # Or adjust according to where your static files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
